version: "3.0"
services:
    db:
        image: mysql:5.7.32
        container_name: db
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=12451fsaf5hgh32
            - MYSQL_DATABASE=webbylab
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=jsdgw351;o94
        ports:
             - 3306:3306
        networks:
            - back
    proxy:
        image: nginx:alpine
        container_name: proxy
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - backend
        networks:
            - back
            - front
    backend:
        container_name: backend
        build: ./backend
        restart: always
        depends_on:
           - db
        volumes:
            - ./backend:/usr/app
        environment:
            - PORT=8080
        networks:
            - back

    frontend:
        container_name: frontend
        build: ./frontend
        restart: always
        volumes: 
            - ./frontend/:/usr/app
        depends_on:
            - backend
        networks:
            - front
    adminer:
        image: adminer
        restart: always
        depends_on: 
            - db
        ports:
            - 9090:8080
        networks:
            - back

networks:
    back:
        driver: bridge
    front:
        driver: bridge