//MAIN
const CHANGE_TITLE = 'CHANGE_TITLE';

//movies
const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

//formats
const FETCH_FORMATS_SUCCESS = 'FETCH_FORMATS_SUCCESS';

//actors
const FETCH_ACTORS_SUCCESS = 'FETCH_ACTORS_SUCCESS';

export {
    CHANGE_TITLE,
    //movies
    FETCH_MOVIES_SUCCESS,
    FETCH_MOVIES_ERROR,
    FETCH_MOVIES_REQUEST,
    //formats
    FETCH_FORMATS_SUCCESS,
    //actors
    FETCH_ACTORS_SUCCESS
}