//MAIN
const CHANGE_TITLE = 'CHANGE_TITLE';

//movies
const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export {
    CHANGE_TITLE,
    //movies
    FETCH_MOVIES_SUCCESS,
    FETCH_MOVIES_ERROR,
    FETCH_MOVIES_REQUEST,
}